### ISSUE TITLE
store import failing when CyberSource payment gateway is imported

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-module-CyberSource#1]
@eMazeika commented on [Wed Sep 28 2016](https://github.com/VirtoCommerce/vc-platform/issues/630)

The whole data import fails if CyberSource payment gateway data is imported. Error:

VirtoCommerce.Store: Error getting value from 'TransactionConfiguration' on 'Cyber.Source.Managers.CyberSourceMethod'.
 Value cannot be null.
 Parameter name: source

Steps to reproduce:
1. install CyberSource payment gateway
2. enable it in selected store
3. export store data using platform data exporter
4. import the exported data back

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog. 
https://virtocommerce.atlassian.net/browse/PRD-106
